export type CountryPhoneOption = {
    code: string;
    label: string;
    minDigits: number;
    maxDigits: number;
};

export const COUNTRY_PHONE_OPTIONS: CountryPhoneOption[] = [
    { code: '+1', label: 'United States / Canada', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Anguilla', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Antigua and Barbuda', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Bahamas', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Barbados', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Bermuda', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'British Virgin Islands', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Cayman Islands', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Dominica', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Dominican Republic', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Grenada', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Jamaica', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Montserrat', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Puerto Rico', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Saint Kitts and Nevis', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Saint Lucia', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Saint Vincent and the Grenadines', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Trinidad and Tobago', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'Turks and Caicos Islands', minDigits: 10, maxDigits: 10 },
    { code: '+1', label: 'U.S. Virgin Islands', minDigits: 10, maxDigits: 10 },
    { code: '+7', label: 'Russia / Kazakhstan', minDigits: 10, maxDigits: 10 },
    { code: '+20', label: 'Egypt', minDigits: 10, maxDigits: 10 },
    { code: '+27', label: 'South Africa', minDigits: 9, maxDigits: 9 },
    { code: '+30', label: 'Greece', minDigits: 10, maxDigits: 10 },
    { code: '+31', label: 'Netherlands', minDigits: 9, maxDigits: 9 },
    { code: '+32', label: 'Belgium', minDigits: 9, maxDigits: 9 },
    { code: '+33', label: 'France', minDigits: 9, maxDigits: 9 },
    { code: '+34', label: 'Spain', minDigits: 9, maxDigits: 9 },
    { code: '+36', label: 'Hungary', minDigits: 8, maxDigits: 9 },
    { code: '+39', label: 'Italy', minDigits: 9, maxDigits: 10 },
    { code: '+40', label: 'Romania', minDigits: 9, maxDigits: 9 },
    { code: '+41', label: 'Switzerland', minDigits: 9, maxDigits: 9 },
    { code: '+43', label: 'Austria', minDigits: 10, maxDigits: 13 },
    { code: '+44', label: 'United Kingdom', minDigits: 9, maxDigits: 10 },
    { code: '+45', label: 'Denmark', minDigits: 8, maxDigits: 8 },
    { code: '+46', label: 'Sweden', minDigits: 7, maxDigits: 9 },
    { code: '+47', label: 'Norway', minDigits: 8, maxDigits: 8 },
    { code: '+48', label: 'Poland', minDigits: 9, maxDigits: 9 },
    { code: '+49', label: 'Germany', minDigits: 10, maxDigits: 11 },
    { code: '+51', label: 'Peru', minDigits: 9, maxDigits: 9 },
    { code: '+52', label: 'Mexico', minDigits: 10, maxDigits: 10 },
    { code: '+53', label: 'Cuba', minDigits: 8, maxDigits: 8 },
    { code: '+54', label: 'Argentina', minDigits: 10, maxDigits: 10 },
    { code: '+55', label: 'Brazil', minDigits: 10, maxDigits: 11 },
    { code: '+56', label: 'Chile', minDigits: 9, maxDigits: 9 },
    { code: '+57', label: 'Colombia', minDigits: 10, maxDigits: 10 },
    { code: '+58', label: 'Venezuela', minDigits: 10, maxDigits: 10 },
    { code: '+60', label: 'Malaysia', minDigits: 9, maxDigits: 10 },
    { code: '+61', label: 'Australia', minDigits: 9, maxDigits: 9 },
    { code: '+62', label: 'Indonesia', minDigits: 9, maxDigits: 11 },
    { code: '+63', label: 'Philippines', minDigits: 10, maxDigits: 10 },
    { code: '+64', label: 'New Zealand', minDigits: 8, maxDigits: 10 },
    { code: '+65', label: 'Singapore', minDigits: 8, maxDigits: 8 },
    { code: '+66', label: 'Thailand', minDigits: 9, maxDigits: 9 },
    { code: '+81', label: 'Japan', minDigits: 10, maxDigits: 10 },
    { code: '+82', label: 'South Korea', minDigits: 9, maxDigits: 10 },
    { code: '+84', label: 'Vietnam', minDigits: 9, maxDigits: 10 },
    { code: '+86', label: 'China', minDigits: 11, maxDigits: 11 },
    { code: '+90', label: 'Turkey', minDigits: 10, maxDigits: 10 },
    { code: '+91', label: 'India', minDigits: 10, maxDigits: 10 },
    { code: '+92', label: 'Pakistan', minDigits: 10, maxDigits: 10 },
    { code: '+93', label: 'Afghanistan', minDigits: 9, maxDigits: 9 },
    { code: '+94', label: 'Sri Lanka', minDigits: 9, maxDigits: 9 },
    { code: '+95', label: 'Myanmar', minDigits: 7, maxDigits: 10 },
    { code: '+98', label: 'Iran', minDigits: 10, maxDigits: 10 },
    { code: '+212', label: 'Morocco', minDigits: 9, maxDigits: 9 },
    { code: '+213', label: 'Algeria', minDigits: 9, maxDigits: 9 },
    { code: '+216', label: 'Tunisia', minDigits: 8, maxDigits: 8 },
    { code: '+218', label: 'Libya', minDigits: 9, maxDigits: 9 },
    { code: '+220', label: 'Gambia', minDigits: 7, maxDigits: 7 },
    { code: '+221', label: 'Senegal', minDigits: 9, maxDigits: 9 },
    { code: '+222', label: 'Mauritania', minDigits: 8, maxDigits: 8 },
    { code: '+223', label: 'Mali', minDigits: 8, maxDigits: 8 },
    { code: '+224', label: 'Guinea', minDigits: 9, maxDigits: 9 },
    { code: '+225', label: 'Ivory Coast', minDigits: 8, maxDigits: 10 },
    { code: '+226', label: 'Burkina Faso', minDigits: 8, maxDigits: 8 },
    { code: '+227', label: 'Niger', minDigits: 8, maxDigits: 8 },
    { code: '+228', label: 'Togo', minDigits: 8, maxDigits: 8 },
    { code: '+229', label: 'Benin', minDigits: 8, maxDigits: 8 },
    { code: '+230', label: 'Mauritius', minDigits: 7, maxDigits: 7 },
    { code: '+231', label: 'Liberia', minDigits: 8, maxDigits: 9 },
    { code: '+232', label: 'Sierra Leone', minDigits: 8, maxDigits: 8 },
    { code: '+233', label: 'Ghana', minDigits: 9, maxDigits: 9 },
    { code: '+234', label: 'Nigeria', minDigits: 10, maxDigits: 10 },
    { code: '+235', label: 'Chad', minDigits: 8, maxDigits: 8 },
    { code: '+236', label: 'Central African Republic', minDigits: 8, maxDigits: 8 },
    { code: '+237', label: 'Cameroon', minDigits: 9, maxDigits: 9 },
    { code: '+238', label: 'Cape Verde', minDigits: 7, maxDigits: 7 },
    { code: '+239', label: 'Sao Tome and Principe', minDigits: 7, maxDigits: 7 },
    { code: '+240', label: 'Equatorial Guinea', minDigits: 9, maxDigits: 9 },
    { code: '+241', label: 'Gabon', minDigits: 8, maxDigits: 9 },
    { code: '+242', label: 'Republic of the Congo', minDigits: 9, maxDigits: 9 },
    { code: '+243', label: 'DR Congo', minDigits: 9, maxDigits: 9 },
    { code: '+244', label: 'Angola', minDigits: 9, maxDigits: 9 },
    { code: '+245', label: 'Guinea-Bissau', minDigits: 7, maxDigits: 7 },
    { code: '+246', label: 'British Indian Ocean Territory', minDigits: 7, maxDigits: 7 },
    { code: '+248', label: 'Seychelles', minDigits: 7, maxDigits: 7 },
    { code: '+249', label: 'Sudan', minDigits: 9, maxDigits: 9 },
    { code: '+250', label: 'Rwanda', minDigits: 9, maxDigits: 9 },
    { code: '+251', label: 'Ethiopia', minDigits: 9, maxDigits: 9 },
    { code: '+252', label: 'Somalia', minDigits: 8, maxDigits: 9 },
    { code: '+253', label: 'Djibouti', minDigits: 8, maxDigits: 8 },
    { code: '+254', label: 'Kenya', minDigits: 9, maxDigits: 9 },
    { code: '+255', label: 'Tanzania', minDigits: 9, maxDigits: 9 },
    { code: '+256', label: 'Uganda', minDigits: 9, maxDigits: 9 },
    { code: '+257', label: 'Burundi', minDigits: 8, maxDigits: 8 },
    { code: '+258', label: 'Mozambique', minDigits: 8, maxDigits: 9 },
    { code: '+260', label: 'Zambia', minDigits: 9, maxDigits: 9 },
    { code: '+261', label: 'Madagascar', minDigits: 9, maxDigits: 9 },
    { code: '+262', label: 'Réunion / Mayotte', minDigits: 9, maxDigits: 9 },
    { code: '+263', label: 'Zimbabwe', minDigits: 9, maxDigits: 9 },
    { code: '+264', label: 'Namibia', minDigits: 9, maxDigits: 9 },
    { code: '+265', label: 'Malawi', minDigits: 9, maxDigits: 9 },
    { code: '+266', label: 'Lesotho', minDigits: 8, maxDigits: 8 },
    { code: '+267', label: 'Botswana', minDigits: 7, maxDigits: 8 },
    { code: '+268', label: 'Eswatini', minDigits: 8, maxDigits: 8 },
    { code: '+269', label: 'Comoros', minDigits: 7, maxDigits: 7 },
    { code: '+290', label: 'Saint Helena', minDigits: 4, maxDigits: 4 },
    { code: '+291', label: 'Eritrea', minDigits: 7, maxDigits: 7 },
    { code: '+297', label: 'Aruba', minDigits: 7, maxDigits: 7 },
    { code: '+298', label: 'Faroe Islands', minDigits: 6, maxDigits: 6 },
    { code: '+299', label: 'Greenland', minDigits: 6, maxDigits: 6 },
    { code: '+350', label: 'Gibraltar', minDigits: 8, maxDigits: 8 },
    { code: '+351', label: 'Portugal', minDigits: 9, maxDigits: 9 },
    { code: '+352', label: 'Luxembourg', minDigits: 8, maxDigits: 9 },
    { code: '+353', label: 'Ireland', minDigits: 9, maxDigits: 9 },
    { code: '+354', label: 'Iceland', minDigits: 7, maxDigits: 7 },
    { code: '+355', label: 'Albania', minDigits: 9, maxDigits: 9 },
    { code: '+356', label: 'Malta', minDigits: 8, maxDigits: 8 },
    { code: '+357', label: 'Cyprus', minDigits: 8, maxDigits: 8 },
    { code: '+358', label: 'Finland', minDigits: 9, maxDigits: 10 },
    { code: '+359', label: 'Bulgaria', minDigits: 9, maxDigits: 9 },
    { code: '+370', label: 'Lithuania', minDigits: 8, maxDigits: 8 },
    { code: '+371', label: 'Latvia', minDigits: 8, maxDigits: 8 },
    { code: '+372', label: 'Estonia', minDigits: 7, maxDigits: 8 },
    { code: '+373', label: 'Moldova', minDigits: 8, maxDigits: 8 },
    { code: '+374', label: 'Armenia', minDigits: 8, maxDigits: 8 },
    { code: '+375', label: 'Belarus', minDigits: 9, maxDigits: 9 },
    { code: '+376', label: 'Andorra', minDigits: 6, maxDigits: 6 },
    { code: '+377', label: 'Monaco', minDigits: 8, maxDigits: 8 },
    { code: '+378', label: 'San Marino', minDigits: 6, maxDigits: 10 },
    { code: '+380', label: 'Ukraine', minDigits: 9, maxDigits: 9 },
    { code: '+381', label: 'Serbia', minDigits: 8, maxDigits: 9 },
    { code: '+382', label: 'Montenegro', minDigits: 8, maxDigits: 8 },
    { code: '+383', label: 'Kosovo', minDigits: 8, maxDigits: 8 },
    { code: '+385', label: 'Croatia', minDigits: 8, maxDigits: 9 },
    { code: '+386', label: 'Slovenia', minDigits: 8, maxDigits: 8 },
    { code: '+387', label: 'Bosnia and Herzegovina', minDigits: 8, maxDigits: 8 },
    { code: '+389', label: 'North Macedonia', minDigits: 8, maxDigits: 8 },
    { code: '+420', label: 'Czech Republic', minDigits: 9, maxDigits: 9 },
    { code: '+421', label: 'Slovakia', minDigits: 9, maxDigits: 9 },
    { code: '+423', label: 'Liechtenstein', minDigits: 7, maxDigits: 9 },
    { code: '+502', label: 'Guatemala', minDigits: 8, maxDigits: 8 },
    { code: '+503', label: 'El Salvador', minDigits: 8, maxDigits: 8 },
    { code: '+504', label: 'Honduras', minDigits: 8, maxDigits: 8 },
    { code: '+505', label: 'Nicaragua', minDigits: 8, maxDigits: 8 },
    { code: '+506', label: 'Costa Rica', minDigits: 8, maxDigits: 8 },
    { code: '+507', label: 'Panama', minDigits: 8, maxDigits: 8 },
    { code: '+508', label: 'Saint Pierre and Miquelon', minDigits: 6, maxDigits: 6 },
    { code: '+509', label: 'Haiti', minDigits: 8, maxDigits: 8 },
    { code: '+590', label: 'Guadeloupe / Martinique / Saint Martin', minDigits: 9, maxDigits: 9 },
    { code: '+591', label: 'Bolivia', minDigits: 8, maxDigits: 8 },
    { code: '+592', label: 'Guyana', minDigits: 7, maxDigits: 7 },
    { code: '+593', label: 'Ecuador', minDigits: 9, maxDigits: 9 },
    { code: '+594', label: 'French Guiana', minDigits: 9, maxDigits: 9 },
    { code: '+595', label: 'Paraguay', minDigits: 9, maxDigits: 9 },
    { code: '+596', label: 'Martinique', minDigits: 9, maxDigits: 9 },
    { code: '+597', label: 'Suriname', minDigits: 6, maxDigits: 7 },
    { code: '+598', label: 'Uruguay', minDigits: 8, maxDigits: 8 },
    { code: '+599', label: 'Curaçao / Caribbean Netherlands', minDigits: 7, maxDigits: 8 },
    { code: '+670', label: 'Timor-Leste', minDigits: 7, maxDigits: 7 },
    { code: '+672', label: 'Antarctica / Norfolk Island', minDigits: 6, maxDigits: 7 },
    { code: '+673', label: 'Brunei', minDigits: 7, maxDigits: 7 },
    { code: '+674', label: 'Nauru', minDigits: 7, maxDigits: 7 },
    { code: '+675', label: 'Papua New Guinea', minDigits: 7, maxDigits: 7 },
    { code: '+676', label: 'Tonga', minDigits: 5, maxDigits: 7 },
    { code: '+677', label: 'Solomon Islands', minDigits: 5, maxDigits: 7 },
    { code: '+678', label: 'Vanuatu', minDigits: 5, maxDigits: 7 },
    { code: '+679', label: 'Fiji', minDigits: 7, maxDigits: 7 },
    { code: '+680', label: 'Palau', minDigits: 7, maxDigits: 7 },
    { code: '+681', label: 'Wallis and Futuna', minDigits: 6, maxDigits: 6 },
    { code: '+682', label: 'Cook Islands', minDigits: 5, maxDigits: 7 },
    { code: '+683', label: 'Niue', minDigits: 4, maxDigits: 7 },
    { code: '+685', label: 'Samoa', minDigits: 5, maxDigits: 7 },
    { code: '+686', label: 'Kiribati', minDigits: 5, maxDigits: 7 },
    { code: '+687', label: 'New Caledonia', minDigits: 6, maxDigits: 6 },
    { code: '+688', label: 'Tuvalu', minDigits: 5, maxDigits: 7 },
    { code: '+689', label: 'French Polynesia', minDigits: 6, maxDigits: 6 },
    { code: '+690', label: 'Tokelau', minDigits: 4, maxDigits: 4 },
    { code: '+691', label: 'Micronesia', minDigits: 7, maxDigits: 7 },
    { code: '+692', label: 'Marshall Islands', minDigits: 7, maxDigits: 7 },
    { code: '+852', label: 'Hong Kong', minDigits: 8, maxDigits: 8 },
    { code: '+853', label: 'Macau', minDigits: 8, maxDigits: 8 },
    { code: '+855', label: 'Cambodia', minDigits: 8, maxDigits: 9 },
    { code: '+856', label: 'Laos', minDigits: 8, maxDigits: 10 },
    { code: '+880', label: 'Bangladesh', minDigits: 10, maxDigits: 10 },
    { code: '+886', label: 'Taiwan', minDigits: 9, maxDigits: 10 },
    { code: '+960', label: 'Maldives', minDigits: 7, maxDigits: 7 },
    { code: '+961', label: 'Lebanon', minDigits: 7, maxDigits: 8 },
    { code: '+962', label: 'Jordan', minDigits: 9, maxDigits: 9 },
    { code: '+963', label: 'Syria', minDigits: 9, maxDigits: 9 },
    { code: '+964', label: 'Iraq', minDigits: 10, maxDigits: 10 },
    { code: '+965', label: 'Kuwait', minDigits: 8, maxDigits: 8 },
    { code: '+966', label: 'Saudi Arabia', minDigits: 9, maxDigits: 9 },
    { code: '+967', label: 'Yemen', minDigits: 9, maxDigits: 9 },
    { code: '+968', label: 'Oman', minDigits: 8, maxDigits: 8 },
    { code: '+970', label: 'Palestine', minDigits: 9, maxDigits: 9 },
    { code: '+971', label: 'United Arab Emirates', minDigits: 9, maxDigits: 9 },
    { code: '+972', label: 'Israel', minDigits: 9, maxDigits: 9 },
    { code: '+973', label: 'Bahrain', minDigits: 8, maxDigits: 8 },
    { code: '+974', label: 'Qatar', minDigits: 8, maxDigits: 8 },
    { code: '+975', label: 'Bhutan', minDigits: 7, maxDigits: 8 },
    { code: '+976', label: 'Mongolia', minDigits: 8, maxDigits: 8 },
    { code: '+977', label: 'Nepal', minDigits: 10, maxDigits: 10 },
    { code: '+992', label: 'Tajikistan', minDigits: 9, maxDigits: 9 },
    { code: '+993', label: 'Turkmenistan', minDigits: 8, maxDigits: 8 },
    { code: '+994', label: 'Azerbaijan', minDigits: 9, maxDigits: 9 },
    { code: '+995', label: 'Georgia', minDigits: 9, maxDigits: 9 },
    { code: '+996', label: 'Kyrgyzstan', minDigits: 9, maxDigits: 9 },
    { code: '+998', label: 'Uzbekistan', minDigits: 9, maxDigits: 9 },
];

export const DEFAULT_COUNTRY_CODE = '+91';

export function getCountryPhoneOption(code: string): CountryPhoneOption {
    return COUNTRY_PHONE_OPTIONS.find((entry) => entry.code === code) || COUNTRY_PHONE_OPTIONS[0];
}

export function formatCountryPhoneHint(option: CountryPhoneOption): string {
    return option.minDigits === option.maxDigits
        ? `${option.minDigits} digits`
        : `${option.minDigits}-${option.maxDigits} digits`;
}

export function parseInternationalPhone(rawPhone: string): { countryCode: string; phone: string } {
    const cleaned = String(rawPhone || '').trim().replace(/[^\d+]/g, '');
    const sortedByCodeLength = [...COUNTRY_PHONE_OPTIONS].sort((a, b) => b.code.length - a.code.length);

    if (cleaned.startsWith('+')) {
        const matched = sortedByCodeLength.find((entry) => cleaned.startsWith(entry.code));
        if (matched) {
                const digits = cleaned.slice(matched.code.length).replace(/\D/g, '').slice(0, matched.maxDigits);
                return { countryCode: matched.code, phone: digits };
        }
    }

    const fallback = getCountryPhoneOption(DEFAULT_COUNTRY_CODE);
    return { countryCode: fallback.code, phone: cleaned.replace(/\D/g, '').slice(0, fallback.maxDigits) };
}
